# Generated by Django 5.0.3 on 2024-03-27 19:23

import med.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_alter_consultationmessage_from_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Doctor'), (2, 'Superuser'), (3, 'User')], default=med.models.UserRoles['USER']),
        ),
    ]
