# Generated by Django 5.0.3 on 2024-03-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0003_remove_user_user_role_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'Doctor'), (2, 'Superuser'), (3, 'User')], default=3, max_length=10),
        ),
    ]
