# Generated by Django 5.0.3 on 2024-03-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
