# Generated by Django 5.0.3 on 2024-03-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=3, max_length=10),
        ),
    ]
