# Generated by Django 5.0.3 on 2024-03-29 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med.consultation'),
        ),
    ]
